// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/division-analytics/DivisionAnalytics.tsx": () => import("../components/mockups/division-analytics/DivisionAnalytics.tsx"),
  "./components/mockups/hr-portal/HRPortal.tsx": () => import("../components/mockups/hr-portal/HRPortal.tsx"),
  "./components/mockups/pdf-report/PDFReport.tsx": () => import("../components/mockups/pdf-report/PDFReport.tsx"),
  "./components/mockups/persistent-db/PersistentDB.tsx": () => import("../components/mockups/persistent-db/PersistentDB.tsx"),
  "./components/mockups/sso-login/SSOLogin.tsx": () => import("../components/mockups/sso-login/SSOLogin.tsx")
};
